#!/usr/bin/env node
import readline from 'node:readline';
import {environment} from './relay-cli.mjs';
import {newId,handoff} from './engine.mjs';
let configured;
async function client(){if(!configured){const c=environment();await c.store.connect();configured=c;}return configured;}
const string={type:'string'};
const definitions=[
 ['relay_read','Read project rules, agent sessions, assignments and recent messages.',{agent_id:string},[]],
 ['relay_claim','Atomically claim an unowned ready task for this agent session.',{task_id:string,operation_id:string},['task_id']],
 ['relay_checkpoint','Save progress and next steps. This does not automatically submit for review.',{task_id:string,checkpoint:string,evidence:string,status:{type:'string',enum:['working','blocked']},operation_id:string},['task_id','checkpoint']],
 ['relay_submit','Submit your task for independent review with actual test results and code links.',{task_id:string,checkpoint:string,evidence:string,operation_id:string},['task_id','checkpoint','evidence']],
 ['relay_message','Post a shared project message, optionally directed to an agent or attached to a task.',{body:string,to:string,task_id:string,operation_id:string},['body']],
 ['relay_question','Ask the project owner for a decision or help with a blocker.',{title:string,body:string,task_id:string,operation_id:string},['title','body']],
 ['relay_review','Review another agent’s submitted task. Self-review is rejected.',{task_id:string,approve:{type:'boolean'},review:string,operation_id:string},['task_id','approve','review']],
 ['relay_checkin','Record contact or a standalone handoff checkpoint.',{checkpoint:string,operation_id:string},[]]
].map(([name,description,properties,required])=>({name,description,inputSchema:{type:'object',properties,required,additionalProperties:false}}));
async function handle(msg){if(msg.method==='initialize')return {protocolVersion:'2024-11-05',capabilities:{tools:{}},serverInfo:{name:'relay-studio',version:'1.0.0'},instructions:'Read the project before acting. All writes use your configured agent and session. Messages are shared project records. Save concrete checkpoints; include test evidence and links. Do not self-review. Never put credentials in messages.'};if(msg.method==='ping')return {};if(msg.method==='tools/list')return {tools:definitions};if(msg.method==='tools/call'){try{const {name,arguments:a={}}=msg.params||{};const c=await client();if(name==='relay_read'){const s=(await c.store.read()).state;const id=a.agent_id||c.actor.id;const own=s.agents.find(x=>x.id===id);return {content:[{type:'text',text:JSON.stringify({revision:s.revision,project:s.project,agent:own,tasks:s.tasks,requests:s.requests.filter(x=>x.status==='open'),memory:s.memory,messages:s.messages.slice(-60),handoff:own?handoff(s,id,c.store.repo):null})}]};}let type,payload;switch(name){case'relay_claim':type='task.claim';payload={taskId:a.task_id};break;case'relay_checkpoint':type='task.progress';payload={taskId:a.task_id,checkpoint:a.checkpoint,evidence:a.evidence,status:a.status||'working'};break;case'relay_submit':type='task.progress';payload={taskId:a.task_id,checkpoint:a.checkpoint,evidence:a.evidence,status:'review'};break;case'relay_message':type='message.add';payload={body:a.body,to:a.to,taskId:a.task_id};break;case'relay_question':type='request.add';payload={title:a.title,body:a.body,taskId:a.task_id};break;case'relay_review':type='task.review';payload={taskId:a.task_id,approve:a.approve,review:a.review};break;case'relay_checkin':type='agent.checkpoint';payload={checkpoint:a.checkpoint};break;default:throw new Error('Unknown tool.');}const id=a.operation_id||newId();const s=await c.store.mutate({id,type,payload},c.actor);return {content:[{type:'text',text:JSON.stringify({ok:true,revision:s.revision,operationId:id})}]};}catch(e){return {isError:true,content:[{type:'text',text:e.message}]};}}throw Object.assign(new Error('Method not found'),{code:-32601});}
const input=readline.createInterface({input:process.stdin,crlfDelay:Infinity});let queue=Promise.resolve();
input.on('line',line=>{queue=queue.then(async()=>{let msg;try{msg=JSON.parse(line);}catch{process.stdout.write(JSON.stringify({jsonrpc:'2.0',id:null,error:{code:-32700,message:'Parse error'}})+'\n');return;}if(msg.id===undefined)return;try{process.stdout.write(JSON.stringify({jsonrpc:'2.0',id:msg.id,result:await handle(msg)})+'\n');}catch(e){process.stdout.write(JSON.stringify({jsonrpc:'2.0',id:msg.id,error:{code:e.code||-32603,message:e.message}})+'\n');}});});
