import {validateState,applyOperation,HubError} from './engine.mjs';
const enc=s=>{const bytes=new TextEncoder().encode(s);let b='';for(const v of bytes)b+=String.fromCharCode(v);return btoa(b);};
const dec=s=>new TextDecoder().decode(Uint8Array.from(atob(s.replace(/\s/g,'')),c=>c.charCodeAt(0)));
export class GitHubStore {
 constructor({repo,token,fetcher=fetch}){if(!/^[a-zA-Z0-9_.-]+\/[a-zA-Z0-9_.-]+$/.test(repo))throw new HubError('Enter a repository as owner/name.');if(!token)throw new HubError('A GitHub access token is required.');this.repo=repo;this.token=token;this.fetcher=fetcher;this.base=`https://api.github.com/repos/${repo}`;this.branch=null;this.queue=Promise.resolve();}
 async request(path,method='GET',body){let r;try{r=await this.fetcher(this.base+path,{method,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${this.token}`,'Content-Type':'application/json','X-GitHub-Api-Version':'2022-11-28'},body:body?JSON.stringify(body):undefined,cache:'no-store'});}catch{throw new HubError('Could not reach GitHub. Your draft is still here. Check your connection and retry.','NETWORK');}let data={};try{data=await r.json();}catch{}if(!r.ok){const e=new HubError(r.status===401?'GitHub sign-in expired or the token is invalid.':r.status===403?'GitHub denied this request. Check token permissions or API rate limits.':r.status===404?'Repository or board not found. Check the name and token access.':r.status===409?'The board changed while saving.':`GitHub could not save this request (${r.status}).`,String(r.status));throw e;}return data;}
 async connect(){const repo=await this.request('');if(!repo.private)throw new HubError('Choose a PRIVATE repository for project data. The website repository is public.','PRIVACY');if(repo.archived)throw new HubError('This repository is archived.');this.branch=repo.default_branch;return repo;}
 async read(){const d=await this.request('/contents/hub-state.json'+(this.branch?'?ref='+encodeURIComponent(this.branch):''));if(d.encoding!=='base64'||!d.content)throw new HubError('The board is too large or has an unsupported format.');return {state:validateState(JSON.parse(dec(d.content))),sha:d.sha};}
 async write(state,sha,message){return this.request('/contents/hub-state.json','PUT',{message,content:enc(JSON.stringify(state,null,2)),...(sha?{sha}:{}),...(this.branch?{branch:this.branch}:{})});}
 async initialize(state){await this.connect();await this.write(state,null,'Initialize Relay project board');return this.read();}
 mutate(op,actor){const job=()=>this.doMutate(op,actor);const result=this.queue.then(job,job);this.queue=result.catch(()=>{});return result;}
 async doMutate(op,actor){for(let attempt=0;attempt<5;attempt++){const {state,sha}=await this.read();const next=applyOperation(state,op,actor);if(next===state)return state;try{await this.write(next,sha,`Relay: ${op.type}`);return next;}catch(e){if(!['409','422','NETWORK'].includes(e.code))throw e;if(e.code==='NETWORK'){try{const check=await this.read();if(check.state.operations.includes(op.id))return check.state;}catch{throw e;}}if(attempt===4)throw new HubError('The board is busy. Your draft is preserved; retry shortly.','CONFLICT');await new Promise(r=>setTimeout(r,150+attempt*180));}}}
 disconnect(){this.token='';}
}
