import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyState,applyOperation,taskAssignees,taskVersion,activeTasks,handoff,HubError} from '../engine.mjs';
import {createHandler} from '../backend/handler.mjs';
const manager={id:'owner',owner:true},forge={id:'forge',session:'forge-session'},scout={id:'scout',session:'scout-session'},reviewer={id:'reviewer',session:'reviewer-session'};
let n=0;const op=(type,payload={},id=`task-test-${++n}`)=>({id,type,payload});
const run=(s,type,payload={},actor=manager)=>applyOperation(s,op(type,payload),actor);
const version=s=>taskVersion(s.tasks.find(t=>t.id==='task'));
const change=(s,type,data={},actor=manager)=>run(s,type,{taskId:'task',expectedVersion:version(s),...data},actor);
function fixture(){let s=emptyState();for(const a of [forge,scout,reviewer]){s=applyOperation(s,op('agent.add',{name:a.id,role:'Builder'},a.id),manager);s=applyOperation(s,op('agent.session',{agentId:a.id},a.session),manager);}return applyOperation(s,op('task.add',{title:'Shared task',acceptance:'All tests pass'},'task'),manager);}
const code=expected=>e=>e.code===expected;
test('multiple assignees are deduplicated; first owner remains a compatible mirror',()=>{let s=change(fixture(),'task.assign',{agentIds:['forge','scout','forge']});assert.deepEqual(taskAssignees(s.tasks[0]),[{agentId:'forge',session:'forge-session'},{agentId:'scout',session:'scout-session'}]);assert.equal(s.tasks[0].owner,'forge');assert.equal(s.tasks[0].session,'forge-session');assert.equal(s.tasks[0].status,'working');});
test('legacy ownership survives edits, JSON round trips, assignment conversion and unrelated operations',()=>{let s=fixture();Object.assign(s.tasks[0],{owner:'forge',session:'forge-session',status:'working',checkpoint:'Preserve me',evidence:'Old evidence'});delete s.tasks[0].assignees;delete s.tasks[0].version;assert.deepEqual(taskAssignees(s.tasks[0]),[{agentId:'forge',session:'forge-session'}]);s=change(s,'task.edit',{title:'Renamed',description:'Scope',acceptance:'Still pass',priority:'high'});s=JSON.parse(JSON.stringify(s));s=run(s,'message.add',{body:'Unrelated'});s=change(s,'task.assign',{agentIds:['forge','scout']});assert.equal(s.tasks[0].checkpoint,'Preserve me');assert.equal(s.tasks[0].evidence,'Old evidence');assert.equal(s.tasks[0].owner,'forge');});
test('manager can create a task with two agents; invalid assignment rolls back atomically',()=>{let s=fixture();const original=structuredClone(s);s=run(s,'task.add',{title:'New shared task',acceptance:'Pass',agentIds:['forge','scout']});assert.equal(s.tasks.at(-1).assignees.length,2);assert.equal(s.tasks.at(-1).status,'working');assert.throws(()=>change(original,'task.assign',{agentIds:['forge','missing']}),code('NOT_FOUND'));assert.equal(original.tasks[0].assignees.length,0);assert.equal(original.tasks[0].version,0);});
test('secondary assignee can make progress and receives own checkpoint and handoff',()=>{let s=change(fixture(),'task.assign',{agentIds:['forge','scout']});s=change(s,'task.progress',{checkpoint:'Scout progress',status:'working'},scout);assert.equal(s.agents.find(a=>a.id==='scout').checkpoint,'Scout progress');assert.equal(s.agents.find(a=>a.id==='forge').checkpoint,'');assert.match(handoff(s,'scout'),/Shared task/);assert.match(handoff(s,'scout'),/Agents: forge, scout/);});
test('every current assignee is excluded from independent review',()=>{let s=change(fixture(),'task.assign',{agentIds:['forge','scout']});s=change(s,'task.progress',{checkpoint:'Complete',status:'review',evidence:'Tests passed'},scout);for(const a of [forge,scout])assert.throws(()=>change(s,'task.review',{approve:true,review:'Approved'},a),code('SELF_REVIEW'));s=change(s,'task.review',{approve:true,review:'Independently verified'},reviewer);assert.equal(s.tasks[0].status,'done');});
test('workers cannot assign, edit, delete or restore, and cannot modify another task',()=>{const s=change(fixture(),'task.assign',{agentIds:['forge']});for(const type of ['task.assign','task.edit','task.delete','task.restore'])assert.throws(()=>change(s,type,{agentIds:['scout']},scout),code('FORBIDDEN'));assert.throws(()=>change(s,'task.progress',{checkpoint:'Not mine'},scout),code('FORBIDDEN'));});
test('unknown, paused and sessionless assignees are rejected without modifying original',()=>{let s=fixture();s.agents[1].enabled=false;s.agents[2].session=null;const before=structuredClone(s);for(const id of ['unknown','scout','reviewer'])assert.throws(()=>change(s,'task.assign',{agentIds:['forge',id]}));assert.deepEqual(s,before);for(const agentIds of [null,'forge',[{}],Array(101).fill('forge')])assert.throws(()=>change(s,'task.assign',{agentIds}));});
test('removing primary promotes secondary; clearing all preserves progress and returns Ready',()=>{let s=change(fixture(),'task.assign',{agentIds:['forge','scout']});s=change(s,'task.progress',{checkpoint:'Keep this'},forge);s=change(s,'task.assign',{agentIds:['scout']});assert.equal(s.tasks[0].owner,'scout');assert.equal(s.tasks[0].session,'scout-session');assert.throws(()=>change(s,'task.progress',{checkpoint:'Removed'},forge),code('FORBIDDEN'));s=change(s,'task.assign',{agentIds:[]});assert.equal(s.tasks[0].owner,null);assert.equal(s.tasks[0].status,'ready');assert.equal(s.tasks[0].checkpoint,'Keep this');});
test('session rotation updates secondary assignment and stale session fails',()=>{let s=change(fixture(),'task.assign',{agentIds:['forge','scout']});s=applyOperation(s,op('agent.session',{agentId:'scout'},'scout-next'),manager);assert.equal(taskAssignees(s.tasks[0])[1].session,'scout-next');assert.equal(s.tasks[0].session,'forge-session');assert.throws(()=>change(s,'task.progress',{checkpoint:'Old'},scout),code('STALE_SESSION'));s=change(s,'task.progress',{checkpoint:'New'}, {...scout,session:'scout-next'});assert.equal(s.tasks[0].checkpoint,'New');});
test('concurrent changes reject stale version, including two writes in the same millisecond',()=>{const s=change(fixture(),'task.assign',{agentIds:['forge','scout']});const v=version(s);const next=change(s,'task.progress',{checkpoint:'New'},forge);for(const type of ['task.assign','task.delete','task.edit','task.progress','task.review','task.release'])assert.throws(()=>run(next,type,{taskId:'task',expectedVersion:v,agentIds:['forge']}),code('CONFLICT'));assert.throws(()=>run(s,'task.assign',{taskId:'task',agentIds:['forge']}),code('CONFLICT'));});
test('soft delete hides work and handoffs; restore preserves exact task history and assignments',()=>{let s=change(fixture(),'task.assign',{agentIds:['forge','scout']});s=change(s,'task.progress',{checkpoint:'Saved',status:'review',evidence:'Evidence'},forge);s=run(s,'message.add',{taskId:'task',body:'Keep conversation'});const before=structuredClone(s.tasks[0]);s=change(s,'task.delete');assert.equal(activeTasks(s).length,0);assert.doesNotMatch(handoff(s,'scout'),/Shared task/);assert.equal(s.messages[0].body,'Keep conversation');assert.throws(()=>change(s,'task.progress',{checkpoint:'Gone'},forge),code('TASK_DELETED'));s=change(s,'task.restore');assert.equal(activeTasks(s).length,1);for(const key of ['id','title','checkpoint','evidence','review','status','assignees','createdAt','createdBy'])assert.deepEqual(s.tasks[0][key],before[key]);assert.equal(s.tasks[0].deletedAt,undefined);});
test('delete/restore retry is idempotent; dependency deletion cannot silently unblock work',()=>{let s=fixture();s=run(s,'task.add',{title:'Dependent',acceptance:'Done',dependencies:['task']});assert.throws(()=>change(s,'task.delete'),code('DEPENDENCY'));const dependent=s.tasks[1];s=run(s,'task.delete',{taskId:dependent.id,expectedVersion:0});const del=op('task.delete',{taskId:'task',expectedVersion:version(s)});s=applyOperation(s,del,manager);assert.strictEqual(applyOperation(s,del,manager),s);assert.throws(()=>run(s,'task.restore',{taskId:dependent.id,expectedVersion:1}),code('DEPENDENCY'));const restore=op('task.restore',{taskId:'task',expectedVersion:version(s)});s=applyOperation(s,restore,manager);assert.strictEqual(applyOperation(s,restore,manager),s);});
test('backend permits manager new operations but rejects worker and spoofed owner payload',async()=>{let state=fixture();let writes=0;const rpc=async(action,token,data)=>{if(action==='context')return {capabilities:{taskLifecycleV1:true},state:structuredClone(state),user:{role:token==='manager'?'manager':'worker'},actor:token==='manager'?manager:scout};if(action==='board.commit'){state=data.state;writes++;return {state};}};const handler=createHandler({rpc,allowedOrigins:[]});const send=async(type,token,payload)=>{const r=await handler(new Request('https://relay.example',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({action:'operation',data:{op:op(type,{taskId:'task',expectedVersion:version(state),...payload})}})}));return {status:r.status,body:await r.json()};};for(const type of ['task.assign','task.edit','task.delete','task.restore'])assert.equal((await send(type,'worker',{owner:true,agentIds:['scout']})).status,403);assert.equal(writes,0);assert.equal((await send('task.assign','manager',{agentIds:['forge','scout']})).status,200);assert.equal((await send('task.delete','manager',{})).status,200);assert.equal((await send('task.restore','manager',{})).status,200);assert.equal(state.tasks[0].assignees.length,2);});
test('backend CAS retry does not overwrite a concurrently edited task',async()=>{let state=fixture(),attempts=0;const rpc=async(action,token,data)=>{if(action==='context')return {capabilities:{taskLifecycleV1:true},state:structuredClone(state),user:{role:'manager'},actor:manager};if(action==='board.commit'){attempts++;state=change(state,'task.assign',{agentIds:['scout']});throw new HubError('Concurrent write','CONFLICT');}};const handler=createHandler({rpc,allowedOrigins:[]});const r=await handler(new Request('https://relay.example',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer manager'},body:JSON.stringify({action:'operation',data:{op:op('task.assign',{taskId:'task',expectedVersion:0,agentIds:['forge']})}})}));assert.equal(r.status,409);assert.equal(attempts,1);assert.equal(state.tasks[0].owner,'scout');});

test('unversioned clients cannot silently overwrite shared-task progress',()=>{const s=change(fixture(),'task.assign',{agentIds:['forge','scout']});for(const type of ['task.progress','task.review','task.release'])assert.throws(()=>run(s,type,{taskId:'task',checkpoint:'Unversioned'},manager),code('CONFLICT'));});

test('MCP bridge exposes and forwards read task versions for shared checkpoint, submit and review',async()=>{const {handle}=await import('../bridge.mjs');let state=change(fixture(),'task.assign',{agentIds:['forge','scout']});let actor=scout;const client=async()=>({store:{base:'https://relay.fixture.invalid',read:async()=>({state,actor,user:{role:'worker'}}),mutate:async operation=>{state=applyOperation(state,operation,actor);return state;}}});const list=await handle({method:'tools/list'});for(const name of ['relay_claim','relay_checkpoint','relay_submit','relay_review'])assert.equal(list.tools.find(t=>t.name===name).inputSchema.properties.expected_version.type,'integer');const call=async(name,args)=>handle({method:'tools/call',params:{name,arguments:args}},client);let result=await call('relay_checkpoint',{task_id:'task',expected_version:version(state),checkpoint:'Bridge shared progress'});assert.equal(result.isError,undefined);assert.equal(state.tasks[0].checkpoint,'Bridge shared progress');const stale=version(state)-1;result=await call('relay_checkpoint',{task_id:'task',expected_version:stale,checkpoint:'Stale bridge progress'});assert.equal(result.isError,true);assert.equal(state.tasks[0].checkpoint,'Bridge shared progress');result=await call('relay_submit',{task_id:'task',expected_version:version(state),checkpoint:'Bridge submit',evidence:'Actual tests'});assert.equal(result.isError,undefined);actor=reviewer;result=await call('relay_review',{task_id:'task',expected_version:version(state),approve:true,review:'Independent bridge review'});assert.equal(result.isError,undefined);assert.equal(state.tasks[0].status,'done');state=change(state,'task.delete');result=await call('relay_read',{});assert.equal(JSON.parse(result.content[0].text).tasks.length,0);});

test('handler announces task controls only when SQL lifecycle capability is ready',async()=>{
 for(const capabilities of [undefined,{}, {taskLifecycleV1:false}, {taskLifecycleV1:true}]){
 const handler=createHandler({rpc:async action=>action==='context'?{user:{role:'worker'},manager:{name:'Ada'},capabilities}:[]});
 const response=await handler(new Request('https://example.invalid',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer test'},body:JSON.stringify({action:'context'})}));
 const body=await response.json();assert.equal(response.status,200);assert.equal(body.capabilities.taskControlsV1,capabilities?.taskLifecycleV1===true);assert.deepEqual(body.manager,{name:'Ada'});
 }
});


test('task operations fail closed without verified SQL lifecycle support and never write',async()=>{
 for(const role of ['manager','worker']) for(const capabilities of [undefined,{}, {taskLifecycleV1:false}, {taskLifecycleV1:'true'}, {taskControlsV1:true}]){
  const calls=[];const state=fixture();
  const handler=createHandler({rpc:async(action)=>{calls.push(action);if(action==='context')return {state:structuredClone(state),user:{role},actor:role==='manager'?manager:scout,capabilities};throw new Error('Unexpected write');}});
  for(const type of ['task.add','task.assign','task.edit','task.delete','task.restore','task.claim','task.progress','task.review','task.release']){
   const response=await handler(new Request('https://example.invalid',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer test'},body:JSON.stringify({action:'operation',data:{op:op(type,{taskId:'task',capabilities:{taskLifecycleV1:true}})}})}));
   assert.equal(response.status,503,type);assert.equal((await response.json()).error.code,'BACKEND_NOT_READY',type);
  }
  assert.equal(calls.length,9);assert.ok(calls.every(action=>action==='context'));
 }
});

test('task compatibility is checked again before retrying a board conflict',async()=>{
 let reads=0,writes=0;const state=fixture();
 const handler=createHandler({rpc:async(action)=>{if(action==='context')return {state:structuredClone(state),user:{role:'manager'},actor:manager,capabilities:{taskLifecycleV1:++reads===1}};if(action==='board.commit'){writes++;throw new HubError('Concurrent write','CONFLICT');}}});
 const response=await handler(new Request('https://example.invalid',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer test'},body:JSON.stringify({action:'operation',data:{op:op('task.add',{title:'New',acceptance:'Verified'})}})}));
 assert.equal(response.status,503);assert.equal((await response.json()).error.code,'BACKEND_NOT_READY');assert.equal(reads,2);assert.equal(writes,1);
});
