import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyState,applyOperation,handoff} from '../engine.mjs';
import {GitHubStore} from '../github.mjs';
const owner={id:'owner',owner:true};
let counter=0;
const op=(type,payload={},id='op-'+(++counter))=>({id,type,payload});
function setup(){let s=emptyState();s=applyOperation(s,op('agent.add',{name:'Forge',role:'Builder'},'forge'),owner);s=applyOperation(s,op('agent.add',{name:'Scout',role:'Tester'},'scout'),owner);s=applyOperation(s,op('agent.session',{agentId:'forge'},'f1'),owner);s=applyOperation(s,op('agent.session',{agentId:'scout'},'s1'),owner);s=applyOperation(s,op('task.add',{title:'Movement',acceptance:'Test turning'},'task'),owner);return s;}
const forge={id:'forge',session:'f1'},scout={id:'scout',session:'s1'};
test('worker claims, checkpoints, submits and independent reviewer approves',()=>{let s=setup();s=applyOperation(s,op('task.claim',{taskId:'task'}),forge);s=applyOperation(s,op('task.progress',{taskId:'task',checkpoint:'Turning implemented',status:'review',evidence:'Three recorded tests passed'}),forge);assert.throws(()=>applyOperation(s,op('task.review',{taskId:'task',approve:true,review:'fine'}),forge),e=>e.code==='SELF_REVIEW');s=applyOperation(s,op('task.review',{taskId:'task',approve:true,review:'Reproduced all tests'}),scout);assert.equal(s.tasks[0].status,'done');assert.equal(s.tasks[0].reviewedBy,'scout');});
test('replaced sessions cannot update; new session inherits task',()=>{let s=applyOperation(setup(),op('task.claim',{taskId:'task'}),forge);s=applyOperation(s,op('agent.session',{agentId:'forge'},'f2'),owner);assert.throws(()=>applyOperation(s,op('task.progress',{taskId:'task',checkpoint:'old',status:'working'}),forge),e=>e.code==='STALE_SESSION');assert.equal(s.tasks[0].session,'f2');s=applyOperation(s,op('task.progress',{taskId:'task',checkpoint:'resumed',status:'working'}),{id:'forge',session:'f2'});assert.equal(s.tasks[0].checkpoint,'resumed');});
test('repeated operation is idempotent',()=>{const operation=op('message.add',{body:'Hello'},'same-message');const s=applyOperation(setup(),operation,forge);assert.strictEqual(applyOperation(s,operation,forge),s);assert.equal(s.messages.length,1);});
test('tasks require dependencies and completion evidence',()=>{let s=setup();s=applyOperation(s,op('task.add',{title:'Dependent task',acceptance:'Done',dependencies:['task']},'dependent'),owner);assert.throws(()=>applyOperation(s,op('task.claim',{taskId:'dependent'}),forge),e=>e.code==='DEPENDENCY');s=applyOperation(s,op('task.claim',{taskId:'task'}),forge);assert.throws(()=>applyOperation(s,op('task.progress',{taskId:'task',checkpoint:'Done',status:'review'}),forge),/evidence/i);});
test('another worker cannot overwrite the owner and paused agents cannot write',()=>{let s=applyOperation(setup(),op('task.claim',{taskId:'task'}),forge);assert.throws(()=>applyOperation(s,op('task.progress',{taskId:'task',checkpoint:'Takeover'}),scout),e=>e.code==='FORBIDDEN');s=applyOperation(s,op('agent.update',{agentId:'forge',enabled:false}),owner);assert.throws(()=>applyOperation(s,op('message.add',{body:'hi'}),forge),e=>e.code==='FORBIDDEN');});
test('note concurrent edits do not silently overwrite',()=>{let s=setup();s=applyOperation(s,op('memory.save',{title:'Decision',body:'old'},'note'),owner,'2026-01-01T00:00:00Z');s=applyOperation(s,op('memory.save',{memoryId:'note',expectedUpdatedAt:'2026-01-01T00:00:00Z',title:'Decision',body:'new'}),owner,'2026-01-02T00:00:00Z');assert.throws(()=>applyOperation(s,op('memory.save',{memoryId:'note',expectedUpdatedAt:'2026-01-01T00:00:00Z',title:'Decision',body:'stale'}),owner),e=>e.code==='CONFLICT');});
test('handoff contains session, task, rules and latest checkpoint',()=>{let s=applyOperation(setup(),op('task.claim',{taskId:'task'}),forge);s=applyOperation(s,op('task.progress',{taskId:'task',checkpoint:'Next: dense formation test'}),forge);const text=handoff(s,'forge','owner/private');assert.match(text,/SESSION ID: f1/);assert.match(text,/dense formation/);assert.match(text,/owner\/private/);assert.match(text,/Test turning/);});
test('unsafe build links are rejected',()=>{assert.throws(()=>applyOperation(setup(),op('build.add',{title:'Bad',url:'javascript:alert(1)',tests:'test'}),owner),/http/);});
function mock(initial,{publicRepo=false,loseResponse=false}={}){let state=structuredClone(initial),sha=1,writes=0;const fetcher=async(url,opts)=>{if(!url.includes('/contents/'))return Response.json({private:!publicRepo,default_branch:'main'});if(opts.method==='GET')return Response.json({sha:String(sha),encoding:'base64',content:Buffer.from(JSON.stringify(state)).toString('base64')});const body=JSON.parse(opts.body);if(body.sha!==String(sha))return Response.json({message:'conflict'},{status:409});state=JSON.parse(Buffer.from(body.content,'base64').toString());sha++;writes++;if(loseResponse&&writes===1)throw new Error('lost');return Response.json({content:{sha:String(sha)}});};return {fetcher,get:()=>state,writes:()=>writes};}
test('two concurrent clients cannot both claim the same task',async()=>{const db=mock(setup());const a=new GitHubStore({repo:'x/private',token:'test',fetcher:db.fetcher});const b=new GitHubStore({repo:'x/private',token:'test',fetcher:db.fetcher});const results=await Promise.allSettled([a.mutate(op('task.claim',{taskId:'task'}),forge),b.mutate(op('task.claim',{taskId:'task'}),scout)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(db.writes(),1);assert.equal(results.find(r=>r.status==='rejected').reason.code,'CLAIMED');});
test('independent concurrent updates both survive retry',async()=>{const db=mock(setup());const a=new GitHubStore({repo:'x/private',token:'test',fetcher:db.fetcher});const b=new GitHubStore({repo:'x/private',token:'test',fetcher:db.fetcher});await Promise.all([a.mutate(op('message.add',{body:'A'}),forge),b.mutate(op('message.add',{body:'B'}),scout)]);assert.deepEqual(db.get().messages.map(m=>m.body).sort(),['A','B']);});
test('lost save acknowledgement does not duplicate a message',async()=>{const db=mock(setup(),{loseResponse:true});const a=new GitHubStore({repo:'x/private',token:'test',fetcher:db.fetcher});await a.mutate(op('message.add',{body:'Once'}),forge);assert.equal(db.writes(),1);assert.equal(db.get().messages.length,1);});
test('public repositories are rejected as storage',async()=>{const db=mock(setup(),{publicRepo:true});const a=new GitHubStore({repo:'x/public',token:'test',fetcher:db.fetcher});await assert.rejects(a.connect(),e=>e.code==='PRIVACY');});
test('resolving a question retains owner decision',()=>{let s=setup();s=applyOperation(s,op('request.add',{title:'Balance?',body:'How much charge damage?'},'q'),forge);s=applyOperation(s,op('request.resolve',{requestId:'q',answer:'Keep current damage until movement tests pass'}),owner);assert.equal(s.requests[0].status,'resolved');assert.match(s.requests[0].answer,/movement/);});
